version: '5.4'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: packing-api
    command: ["./packing-server", "--otel-endpoint=jaeger:4318"]
    depends_on:
      - jaeger

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # maps the container's Nginx port 80 to your local port 3000
    restart: unless-stopped
    container_name: packing-ui
    depends_on:
      - backend

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # The Jaeger UI (Open this in your browser)
      - "4317:4317"   # OTLP gRPC receiver (For Go to send data)
      - "4318:4318"   # OTLP HTTP receiver (For Go to send data)
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped