// Code generated by MockGen. DO NOT EDIT.
// Source: item-packing-calculator/internal/core/ports (interfaces: PackStorage)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPackStorage is a mock of PackStorage interface.
type MockPackStorage struct {
	ctrl     *gomock.Controller
	recorder *MockPackStorageMockRecorder
}

// MockPackStorageMockRecorder is the mock recorder for MockPackStorage.
type MockPackStorageMockRecorder struct {
	mock *MockPackStorage
}

// NewMockPackStorage creates a new mock instance.
func NewMockPackStorage(ctrl *gomock.Controller) *MockPackStorage {
	mock := &MockPackStorage{ctrl: ctrl}
	mock.recorder = &MockPackStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackStorage) EXPECT() *MockPackStorageMockRecorder {
	return m.recorder
}

// DeleteSize mocks base method.
func (m *MockPackStorage) DeleteSize(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSize", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSize indicates an expected call of DeleteSize.
func (mr *MockPackStorageMockRecorder) DeleteSize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSize", reflect.TypeOf((*MockPackStorage)(nil).DeleteSize), arg0, arg1)
}

// GetSizes mocks base method.
func (m *MockPackStorage) GetSizes(arg0 context.Context) []int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSizes", arg0)
	ret0, _ := ret[0].([]int)
	return ret0
}

// GetSizes indicates an expected call of GetSizes.
func (mr *MockPackStorageMockRecorder) GetSizes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSizes", reflect.TypeOf((*MockPackStorage)(nil).GetSizes), arg0)
}

// SaveSize mocks base method.
func (m *MockPackStorage) SaveSize(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSize", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSize indicates an expected call of SaveSize.
func (mr *MockPackStorageMockRecorder) SaveSize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSize", reflect.TypeOf((*MockPackStorage)(nil).SaveSize), arg0, arg1)
}
