// Code generated by MockGen. DO NOT EDIT.
// Source: item-packing-calculator/internal/core/ports (interfaces: PackService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "item-packing-calculator/internal/core/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPackService is a mock of PackService interface.
type MockPackService struct {
	ctrl     *gomock.Controller
	recorder *MockPackServiceMockRecorder
}

// MockPackServiceMockRecorder is the mock recorder for MockPackService.
type MockPackServiceMockRecorder struct {
	mock *MockPackService
}

// NewMockPackService creates a new mock instance.
func NewMockPackService(ctrl *gomock.Controller) *MockPackService {
	mock := &MockPackService{ctrl: ctrl}
	mock.recorder = &MockPackServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackService) EXPECT() *MockPackServiceMockRecorder {
	return m.recorder
}

// AddSize mocks base method.
func (m *MockPackService) AddSize(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSize", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSize indicates an expected call of AddSize.
func (mr *MockPackServiceMockRecorder) AddSize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSize", reflect.TypeOf((*MockPackService)(nil).AddSize), arg0, arg1)
}

// Calculate mocks base method.
func (m *MockPackService) Calculate(arg0 context.Context, arg1 int) (domain.CalculationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", arg0, arg1)
	ret0, _ := ret[0].(domain.CalculationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Calculate indicates an expected call of Calculate.
func (mr *MockPackServiceMockRecorder) Calculate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockPackService)(nil).Calculate), arg0, arg1)
}

// RemoveSize mocks base method.
func (m *MockPackService) RemoveSize(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSize", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveSize indicates an expected call of RemoveSize.
func (mr *MockPackServiceMockRecorder) RemoveSize(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSize", reflect.TypeOf((*MockPackService)(nil).RemoveSize), arg0, arg1)
}
